"""
SQL safety validation for AI-generated queries.

Since this application executes SQL generated by an LLM, we apply strict
validation to ensure only safe read-only SELECT queries are executed.
"""

import re
from typing import Optional

from config import get_logger

logging = get_logger(__name__)

# Statements that are strictly forbidden
FORBIDDEN_STATEMENTS = {
    "DROP", "DELETE", "INSERT", "UPDATE", "ALTER", "TRUNCATE",
    "CREATE", "GRANT", "REVOKE", "RENAME", "COMMENT", "EXEC",
    "EXECUTE", "CALL", "MERGE", "SET",  # SET is handled separately for search_path
}

# Dangerous keywords that indicate DML/DDL even inside subqueries
_DANGEROUS_KEYWORDS_RE = re.compile(
    r"\b(?:"
    r"INSERT\s+INTO|UPDATE\s+\w+\s+SET|DELETE\s+FROM|DROP\s+(?:TABLE|VIEW|SCHEMA|DATABASE|INDEX|FUNCTION|TRIGGER)"
    r"|ALTER\s+(?:TABLE|VIEW|SCHEMA|DATABASE|INDEX|FUNCTION|TRIGGER)"
    r"|TRUNCATE\s+TABLE|CREATE\s+(?:TABLE|VIEW|SCHEMA|INDEX|FUNCTION|TRIGGER)"
    r"|GRANT\s|REVOKE\s|MERGE\s+INTO"
    r")\b",
    re.IGNORECASE,
)

# SQL injection red flags
_INJECTION_RED_FLAGS_RE = re.compile(
    r"(?:"
    r";\s*(?:DROP|DELETE|INSERT|UPDATE|ALTER|TRUNCATE|CREATE|GRANT|REVOKE|EXEC)"  # stacked queries
    r"|--\s*(?:DROP|DELETE|INSERT|UPDATE)"  # comment + dangerous statement
    r"|xp_cmdshell|sp_executesql|INFORMATION_SCHEMA\.\s*TABLES"
    r"|UNION\s+(?:ALL\s+)?SELECT\s+.+\s+FROM\s+pg_"
    r"|LOAD_FILE\s*\(|INTO\s+(?:OUTFILE|DUMPFILE)"
    r")",
    re.IGNORECASE,
)

# Allowed identifier characters (letters, digits, underscores, dots for schema.table)
_IDENTIFIER_RE = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_.]*$")


def validate_sql(sql: str, allowed_tables: Optional[set] = None) -> str:
    """
    Validate AI-generated SQL to ensure it's a safe, read-only SELECT query.

    Args:
        sql: The AI-generated SQL query to validate.
        allowed_tables: Optional set of allowed table names. If provided,
            the FROM clause will be checked against this list.

    Returns:
        The cleaned SQL query if valid.

    Raises:
        ValueError: If the SQL query fails safety validation.
    """
    if not sql or not isinstance(sql, str):
        raise ValueError("SQL query must be a non-empty string.")

    # Step 1: Strip markdown code fences
    sql = _strip_code_fences(sql)

    # Step 2: Split into statement and trailing semicolons (multiple statements = dangerous)
    sql_stripped = sql.rstrip(";").strip()

    if not sql_stripped:
        raise ValueError("Empty SQL query after cleanup.")

    # Step 3: Reject multiple statements (anything after the first semicolon)
    if ";" in sql_stripped:
        raise ValueError(
            "Multiple SQL statements are not allowed. "
            "Received a query with semicolons indicating multiple statements."
        )

    # Step 4: Extract the leading keyword and verify it's a SELECT
    first_word = sql_stripped.split()[0].upper()
    if first_word != "SELECT":
        raise ValueError(
            f"Only SELECT queries are allowed. Received: {first_word}."
        )

    # Step 5: Check for forbidden DML/DDL keywords (covers subqueries too)
    if _DANGEROUS_KEYWORDS_RE.search(sql_stripped):
        raise ValueError(
            "SQL query contains forbidden DML/DDL keywords "
            "(INSERT, UPDATE, DELETE, DROP, ALTER, CREATE, TRUNCATE, GRANT, REVOKE, MERGE)."
        )

    # Step 6: Check for SQL injection patterns
    if _INJECTION_RED_FLAGS_RE.search(sql_stripped):
        raise ValueError(
            "SQL query contains patterns associated with SQL injection attacks."
        )

    # Step 7: Validate identifiers in FROM/JOIN clauses
    _validate_table_references(sql_stripped)

    # Step 8: Validate against allowed tables if provided
    if allowed_tables:
        referenced = _extract_table_references(sql_stripped)
        for table in referenced:
            if table not in allowed_tables:
                raise ValueError(
                    f"Referenced table '{table}' is not in the allowed tables list."
                )

    logging.info("SQL query passed safety validation.")
    return sql_stripped


def _strip_code_fences(sql: str) -> str:
    """Remove markdown code fences (```sql ... ```) from the query."""
    sql = sql.strip()
    match = re.match(r"^```(?:sql)?\s*\n?(.*?)\n?\s*```$", sql, re.DOTALL | re.IGNORECASE)
    if match:
        return match.group(1).strip()
    return sql


def validate_identifier(name: str, label: str = "identifier") -> str:
    """
    Validate that a name is a safe SQL identifier (no injection possible).

    Args:
        name: The identifier to validate.
        label: Human-readable label for error messages.

    Returns:
        The validated identifier.

    Raises:
        ValueError: If the identifier contains invalid characters.
    """
    if not name or not isinstance(name, str):
        raise ValueError(f"{label} must be a non-empty string.")
    if not _IDENTIFIER_RE.match(name):
        raise ValueError(
            f"Invalid {label}: '{name}'. "
            "Only letters, digits, underscores, and dots are allowed."
        )
    return name


def validate_search_path(schema_name: str) -> str:
    """Validate a PostgreSQL search_path schema name."""
    return validate_identifier(schema_name, label="schema name")


def _validate_table_references(sql: str) -> None:
    """Check that table names in FROM/JOIN clauses use safe identifiers."""
    table_pattern = re.compile(
        r"(?:FROM|JOIN)\s+([a-zA-Z_][a-zA-Z0-9_.]*)",
        re.IGNORECASE,
    )
    for match in table_pattern.finditer(sql):
        table_name = match.group(1)
        # Allow SQL keywords like "information_schema" (legitimate PostgreSQL system table)
        if table_name.lower() in ("information_schema",):
            continue
        if not _IDENTIFIER_RE.match(table_name):
            raise ValueError(
                f"Table name '{table_name}' contains invalid characters."
            )


def _extract_table_references(sql: str) -> set:
    """Extract table names referenced in FROM/JOIN clauses."""
    table_pattern = re.compile(
        r"(?:FROM|JOIN)\s+([a-zA-Z_][a-zA-Z0-9_.]*)",
        re.IGNORECASE,
    )
    tables = set()
    for match in table_pattern.finditer(sql):
        table_name = match.group(1).lower()
        # Remove schema prefix if present (e.g., "public.users" -> "users")
        if "." in table_name:
            table_name = table_name.split(".")[-1]
        tables.add(table_name)
    return tables
