# __init__.py

from .logger_config import get_logger
from .logger_config import LOG_PROMPTS

# ---------------- Database Config ----------------
from .settings import (
    DB_USERNAME,
    DB_PASSWORD,
    DB_HOST,
    DB_PORT,
    DB_MIN_CONN,
    DB_MAX_CONN,
    KNOWLEDGEBASE_DATABASE_NAME,
    KNOWLEDGEBASE_SCHEMA_NAME,
    KNOWLEDGEBASE_TABLE,
    DATA_SCHEMA,
    USER_DETAILS_SCHEMA,
    SCHEMA_CACHE_TTL_SECONDS,
    AI_SQL_STATEMENT_TIMEOUT_MS,
    AI_SQL_COUNT_TIMEOUT_MS,
)

DB_CONFIG = {
    "DB_USERNAME": DB_USERNAME,
    "DB_PASSWORD": DB_PASSWORD,
    "DB_HOST": DB_HOST,
    "DB_PORT": DB_PORT,
    "DB_MIN_CONN": DB_MIN_CONN,
    "DB_MAX_CONN": DB_MAX_CONN,
    "KNOWLEDGEBASE_DATABASE_NAME": KNOWLEDGEBASE_DATABASE_NAME,
    "KNOWLEDGEBASE_SCHEMA_NAME": KNOWLEDGEBASE_SCHEMA_NAME,
    "KNOWLEDGEBASE_TABLE": KNOWLEDGEBASE_TABLE,
    "DATA_SCHEMA": DATA_SCHEMA,
    "USER_DETAILS_SCHEMA": USER_DETAILS_SCHEMA,
    "SCHEMA_CACHE_TTL_SECONDS": SCHEMA_CACHE_TTL_SECONDS,
    "AI_SQL_STATEMENT_TIMEOUT_MS": AI_SQL_STATEMENT_TIMEOUT_MS,
    "AI_SQL_COUNT_TIMEOUT_MS": AI_SQL_COUNT_TIMEOUT_MS,
}


# ---------------- LLM Context Config ----------------
from .settings import KB_CONTEXT_LIMIT, CONTEXT_LIMIT, NUMBER_OF_CHAT_EXCHANGES

LLM_CONTEXT_CONFIG = {
    "KB_CONTEXT_LIMIT": KB_CONTEXT_LIMIT,
    "CONTEXT_LIMIT": CONTEXT_LIMIT,
    "NUMBER_OF_CHAT_EXCHANGES": NUMBER_OF_CHAT_EXCHANGES,
}


# ---------------- AWS Config ----------------
from .settings import (
    AWS_REGION,
    EMBEDDING_MODEL_ID,
    CHAT_MODEL_ID,
    SQL_MODEL_ID,
    CLASSIFICATION_MODEL_ID,
    JUDGE_MODEL_ID,
    AWS_ACCESS_KEY,
    AWS_SECRET_KEY,
    BEDROCK_CONNECT_TIMEOUT,
    BEDROCK_READ_TIMEOUT,
    BEDROCK_MAX_ATTEMPTS,
    BEDROCK_EXECUTOR_THREADS,
)

AWS_CONFIG = {
    "AWS_REGION": AWS_REGION,
    "EMBEDDING_MODEL_ID": EMBEDDING_MODEL_ID,
    "CHAT_MODEL_ID": CHAT_MODEL_ID,
    "SQL_MODEL_ID": SQL_MODEL_ID,
    "CLASSIFICATION_MODEL_ID": CLASSIFICATION_MODEL_ID,
    "JUDGE_MODEL_ID": JUDGE_MODEL_ID,
    "AWS_ACCESS_KEY": AWS_ACCESS_KEY,
    "AWS_SECRET_KEY": AWS_SECRET_KEY,
    "BEDROCK_CONNECT_TIMEOUT": BEDROCK_CONNECT_TIMEOUT,
    "BEDROCK_READ_TIMEOUT": BEDROCK_READ_TIMEOUT,
    "BEDROCK_MAX_ATTEMPTS": BEDROCK_MAX_ATTEMPTS,
    "BEDROCK_EXECUTOR_THREADS": BEDROCK_EXECUTOR_THREADS,
}


# ---------------- Embedding Model Config ----------------
from .settings import (
    EMBEDDING_MODEL_CONTENT_TYPE,
    EMBEDDING_MODEL_ACCEPT,
    EMBEDDING_MODEL_DIMENSIONS,
    EMBEDDING_MODEL_NORMALIZATION,
    EMBEDDING_CACHE_MAX_ENTRIES,
)

EMBEDDING_MODEL_CONFIG = {
    "EMBEDDING_MODEL_CONTENT_TYPE": EMBEDDING_MODEL_CONTENT_TYPE,
    "EMBEDDING_MODEL_ACCEPT": EMBEDDING_MODEL_ACCEPT,
    "EMBEDDING_MODEL_DIMENSIONS": EMBEDDING_MODEL_DIMENSIONS,
    "EMBEDDING_MODEL_NORMALIZATION": EMBEDDING_MODEL_NORMALIZATION,
    "EMBEDDING_CACHE_MAX_ENTRIES": EMBEDDING_CACHE_MAX_ENTRIES,
}


# ---------------- Chat Model Config ----------------
from .settings import (
    CHAT_MODEL_CONTENT_TYPE,
    CHAT_MODEL_ACCEPT,
    CHAT_MODEL_MAX_GEN_LENGTH,
    CHAT_MODEL_TEMPERATURE,
    CHAT_MODEL_TOP_P,
)

CHAT_MODEL_CONFIG = {
    "CHAT_MODEL_CONTENT_TYPE": CHAT_MODEL_CONTENT_TYPE,
    "CHAT_MODEL_ACCEPT": CHAT_MODEL_ACCEPT,
    "CHAT_MODEL_MAX_GEN_LENGTH": CHAT_MODEL_MAX_GEN_LENGTH,
    "CHAT_MODEL_TEMPERATURE": CHAT_MODEL_TEMPERATURE,
    "CHAT_MODEL_TOP_P": CHAT_MODEL_TOP_P,
}


# ---------------- Classification Model Config ----------------
from .settings import (
    CLASSIFICATION_MODEL_CONTENT_TYPE,
    CLASSIFICATION_MODEL_ACCEPT,
    CLASSIFICATION_MODEL_MAX_GEN_LENGTH,
    CLASSIFICATION_MODEL_TEMPERATURE,
    CLASSIFICATION_MODEL_TOP_P,
)

CLASSIFICATION_MODEL_CONFIG = {
    "CLASSIFICATION_MODEL_CONTENT_TYPE": CLASSIFICATION_MODEL_CONTENT_TYPE,
    "CLASSIFICATION_MODEL_ACCEPT": CLASSIFICATION_MODEL_ACCEPT,
    "CLASSIFICATION_MODEL_MAX_GEN_LENGTH": CLASSIFICATION_MODEL_MAX_GEN_LENGTH,
    "CLASSIFICATION_MODEL_TEMPERATURE": CLASSIFICATION_MODEL_TEMPERATURE,
    "CLASSIFICATION_MODEL_TOP_P": CLASSIFICATION_MODEL_TOP_P,
}


# ---------------- Tracing Config ----------------
from .settings import (
    COLLECTOR_PROJECT_NAME,
    COLLECTOR_ENDPOINT,
    PHOENIX_API_KEY,
    PHOENIX_BATCH,
    PHOENIX_DEBUG,
)

TRACING_CONFIG = {
    "COLLECTOR_PROJECT_NAME": COLLECTOR_PROJECT_NAME,
    "COLLECTOR_ENDPOINT": COLLECTOR_ENDPOINT,
    "PHOENIX_API_KEY": PHOENIX_API_KEY,
    "PHOENIX_BATCH": PHOENIX_BATCH,
    "PHOENIX_DEBUG": PHOENIX_DEBUG,
}


# ---------------- Public Exports ----------------
__all__ = [
    "get_logger",
    "LOG_PROMPTS",
    # Database
    "DB_USERNAME",
    "DB_PASSWORD",
    "DB_HOST",
    "DB_PORT",
    "DB_MIN_CONN",
    "DB_MAX_CONN",
    "KNOWLEDGEBASE_DATABASE_NAME",
    "KNOWLEDGEBASE_SCHEMA_NAME",
    "KNOWLEDGEBASE_TABLE",
    "DATA_SCHEMA",
    "USER_DETAILS_SCHEMA",
    "SCHEMA_CACHE_TTL_SECONDS",
    "AI_SQL_STATEMENT_TIMEOUT_MS",
    "AI_SQL_COUNT_TIMEOUT_MS",
    "DB_CONFIG",
    # LLM Context
    "KB_CONTEXT_LIMIT",
    "CONTEXT_LIMIT",
    "NUMBER_OF_CHAT_EXCHANGES",
    "LLM_CONTEXT_CONFIG",
    # AWS
    "AWS_REGION",
    "EMBEDDING_MODEL_ID",
    "CHAT_MODEL_ID",
    "SQL_MODEL_ID",
    "CLASSIFICATION_MODEL_ID",
    "JUDGE_MODEL_ID",
    "AWS_ACCESS_KEY",
    "AWS_SECRET_KEY",
    "BEDROCK_CONNECT_TIMEOUT",
    "BEDROCK_READ_TIMEOUT",
    "BEDROCK_MAX_ATTEMPTS",
    "BEDROCK_EXECUTOR_THREADS",
    "AWS_CONFIG",
    # Embedding
    "EMBEDDING_MODEL_CONTENT_TYPE",
    "EMBEDDING_MODEL_ACCEPT",
    "EMBEDDING_MODEL_DIMENSIONS",
    "EMBEDDING_MODEL_NORMALIZATION",
    "EMBEDDING_CACHE_MAX_ENTRIES",
    "EMBEDDING_MODEL_CONFIG",
    # Chat
    "CHAT_MODEL_CONTENT_TYPE",
    "CHAT_MODEL_ACCEPT",
    "CHAT_MODEL_MAX_GEN_LENGTH",
    "CHAT_MODEL_TEMPERATURE",
    "CHAT_MODEL_TOP_P",
    "CHAT_MODEL_CONFIG",
    # Classification
    "CLASSIFICATION_MODEL_CONTENT_TYPE",
    "CLASSIFICATION_MODEL_ACCEPT",
    "CLASSIFICATION_MODEL_MAX_GEN_LENGTH",
    "CLASSIFICATION_MODEL_TEMPERATURE",
    "CLASSIFICATION_MODEL_TOP_P",
    "CLASSIFICATION_MODEL_CONFIG",
    # Tracing
    "COLLECTOR_PROJECT_NAME",
    "COLLECTOR_ENDPOINT",
    "PHOENIX_API_KEY",
    "PHOENIX_BATCH",
    "PHOENIX_DEBUG",
    "TRACING_CONFIG",
]
