import os
from dotenv import load_dotenv

load_dotenv()

# Database Connection Details
DB_USERNAME = os.getenv("DB_USERNAME")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_MIN_CONN=2
DB_MAX_CONN=5
KNOWLEDGEBASE_DATABASE_NAME = "maintwiz"
KNOWLEDGEBASE_SCHEMA_NAME = "ai"

DATA_SCHEMA="ai"
USER_DETAILS_SCHEMA="public"

# LLM CONTEXT SETTINGS
KB_CONTEXT_LIMIT=10
CONTEXT_LIMIT=10
NUMBER_OF_CHAT_EXCHANGES=10

# AWS Configurations
AWS_REGION = os.getenv("AWS_REGION")
EMBEDDING_MODEL_ID = os.getenv("BEDROCK_MODEL_ID_TITAN")
CHAT_MODEL_ID = os.getenv("BEDROCK_MODEL_ID_LLAMA")
CLASSIFICATION_MODEL_ID = os.getenv("BEDROCK_MODEL_ID_CLASSIFICATION")
AWS_ACCESS_KEY=os.getenv("AWS_ACCESS_KEY")
AWS_SECRET_KEY=os.getenv("AWS_SECRET_KEY")

# Embedding Model Parameters
EMBEDDING_MODEL_CONTENT_TYPE: str="application/json"
EMBEDDING_MODEL_ACCEPT: str="*/*"
EMBEDDING_MODEL_DIMENSIONS: int=1024
EMBEDDING_MODEL_NORMALIZATION: bool=True

# Chat Model Parameters
CHAT_MODEL_CONTENT_TYPE: str="application/json"
CHAT_MODEL_ACCEPT: str="application/json"
CHAT_MODEL_MAX_GEN_LENGTH=8192
CHAT_MODEL_TEMPERATURE=0.1
CHAT_MODEL_TOP_P=0.9

# Classification Model Parameters
CLASSIFICATION_MODEL_CONTENT_TYPE: str="application/json"
CLASSIFICATION_MODEL_ACCEPT: str="application/json"
CLASSIFICATION_MODEL_MAX_GEN_LENGTH=100
CLASSIFICATION_MODEL_TEMPERATURE=0.1
CLASSIFICATION_MODEL_TOP_P=0.9


# LLM Tracing Tool
COLLECTOR_PROJECT_NAME=os.getenv("COLLECTOR_PROJECT_NAME", "async-mw-copilot-sql-bot-bedrock")
COLLECTOR_ENDPOINT=os.getenv("COLLECTOR_ENDPOINT", "http://maintverse.com:6006/v1/traces")
PHOENIX_API_KEY=os.getenv("PHOENIX_API_KEY")
PHOENIX_BATCH=os.getenv("PHOENIX_BATCH", "True").lower() == "true"
PHOENIX_DEBUG=os.getenv("PHOENIX_DEBUG", "False").lower() == "true"
