# __init__.py

from .user_query_processing import get_last_and_current_user_query as get_last_and_current_user_query
from .user_query_processing import get_last_n_user_queries as get_last_n_user_queries