from fastapi import status, HTTPException
import time
import asyncio
import functools

## Internal Packages
from config import get_logger
<<<<<<< HEAD
from database import execute_ai_generated_sql, format_sql_query
=======
from database import execute_ai_generated_sql, clean_sql_query
>>>>>>> origin/main

## Initiate Logger
logging = get_logger(__name__)

<<<<<<< HEAD
async def sql_agent(start_time, sql_generation_prompt, client_dbconnection_pool, text_generation_model, span, event_loop, trace, facm_code):
=======
async def sql_agent(start_time, sql_generation_prompt, client_dbconnection_pool, text_generation_model, span, event_loop, trace):
>>>>>>> origin/main
    
    ## Give prompt to the LLM to generate SQL
    # sql = text_generation_model.generate_response(sql_generation_prompt)
    
    def _sql_generation(sql_generation_prompt, span):
        with trace.use_span(span):
            return text_generation_model.generate_response(sql_generation_prompt)
<<<<<<< HEAD
        
=======

>>>>>>> origin/main
    sql_result = await asyncio.gather(event_loop.run_in_executor(None, 
                        functools.partial(_sql_generation, sql_generation_prompt, span)
                        ))
    
<<<<<<< HEAD
    raw_sql = sql_result[0]

    span.set_attributes({
                "llm.output_messages.0.message.role": "assistant",
                "llm.output_messages.0.message.content":  str(raw_sql),
            })
    
    if not raw_sql or not isinstance(raw_sql, str):
        error_msg = f"SQL not generated by language model. AI Output: {raw_sql}"
=======
    sql = sql_result[0]

    span.set_attributes({
                "llm.output_messages.0.message.role": "assistant",
                "llm.output_messages.0.message.content":  str(sql),
            })

    if not sql or not isinstance(sql, str):
        error_msg = f"SQL not generated by language model. AI Output: {sql}"
>>>>>>> origin/main
        logging.error(error_msg)
        
        process_time = time.time() - start_time
        
        # Raise exception that FastAPI will convert into a response
<<<<<<< HEAD
        span.record_exception(Exception("SQL not generated by language model."))
=======
        span.record_exception("SQL not generated by language model.")
>>>>>>> origin/main
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="SQL not generated by language model.",
            headers={"X-Response-Time": f"{process_time:.6f} seconds"}
        )
    
<<<<<<< HEAD
    sql = format_sql_query(raw_sql, facm_code)
    
=======
    sql = clean_sql_query(sql)

>>>>>>> origin/main
    if sql == "SELECT 'User request cannot be fulfilled.';" or sql == "SELECT 'User request cannot be fulfilled.'":
        logging.info("User request cannot be fulfilled. SQL: %s", sql)

        process_time = time.time() - start_time
        
        # Raise exception that FastAPI will convert into a response
<<<<<<< HEAD
        span.record_exception(Exception("LLM Generated: SELECT 'User request cannot be fulfilled.'"))
=======
        span.record_exception("LLM Generated: SELECT 'User request cannot be fulfilled.'")
>>>>>>> origin/main
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="User request cannot be fulfilled.",
            headers={"X-Response-Time": f"{process_time:.6f} seconds"}
        )
    
    return await execute_ai_generated_sql(sql, client_dbconnection_pool)