from fastapi import status, HTTPException
import time
import asyncio
import functools
from typing import NamedTuple

## Internal Packages
from config import get_logger
from database import execute_ai_generated_sql, format_sql_query, clean_sql_query
from models import get_bedrock_executor

## Initiate Logger
logging = get_logger(__name__)


class SqlAgentResult(NamedTuple):
    """
    What the SQL agent produced for one request.

    ``sql_template`` keeps the <facilitycode> placeholder unsubstituted so that
    follow-up pagination can re-substitute it against the *current* request's
    facility codes; ``executed_sql`` is the validated statement that actually
    ran.
    """

    sql_template: str
    executed_sql: str
    rows: list


async def sql_agent(
    start_time,
    sql_generation_prompt,
    client_dbconnection_pool,
    text_generation_model,
    span,
    event_loop,
    trace,
    facm_code,
):

    ## Give prompt to the LLM to generate SQL
    # sql = text_generation_model.generate_response(sql_generation_prompt)

    def _sql_generation(sql_generation_prompt, span):
        with trace.use_span(span):
            return text_generation_model.generate_response(
                sql_generation_prompt, span=span
            )

    import contextvars

    ctx_copied = contextvars.copy_context()
    sql_result = await asyncio.gather(
        event_loop.run_in_executor(
            get_bedrock_executor(),
            ctx_copied.run,
            functools.partial(_sql_generation, sql_generation_prompt, span),
        )
    )

    raw_sql = sql_result[0]

    span.set_attributes(
        {
            "llm.output_messages.0.message.role": "assistant",
            "llm.output_messages.0.message.content": str(raw_sql),
        }
    )

    if not raw_sql or not isinstance(raw_sql, str):
        error_msg = f"SQL not generated by language model. AI Output: {raw_sql}"
        logging.error(error_msg)

        process_time = time.time() - start_time

        # Raise exception that FastAPI will convert into a response
        span.record_exception(Exception("SQL not generated by language model."))
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="SQL not generated by language model.",
            headers={"X-Response-Time": f"{process_time:.6f} seconds"},
        )

    from database.sql_safety import validate_sql

    # Fence-stripped but placeholder-preserving, so pagination can re-scope it
    # to whatever facility codes the follow-up request carries.
    sql_template = clean_sql_query(raw_sql).strip().rstrip(";").strip()

    sql = format_sql_query(raw_sql, facm_code)
    if (
        sql == "SELECT 'User request cannot be fulfilled.';"
        or sql == "SELECT 'User request cannot be fulfilled.'"
    ):
        logging.info("User request cannot be fulfilled. SQL: %s", sql)

        process_time = time.time() - start_time

        # Raise exception that FastAPI will convert into a response
        span.record_exception(
            Exception("LLM Generated: SELECT 'User request cannot be fulfilled.'")
        )
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="User request cannot be fulfilled.",
            headers={"X-Response-Time": f"{process_time:.6f} seconds"},
        )

    # VERY IMPORTANT: Validate the AI-generated SQL for safety (No DROP, UPDATE, DELETE, or multiple statements)
    try:
        sql = validate_sql(sql)
    except ValueError as safety_error:
        logging.error(f"SQL Safety Validation Failed: {safety_error} | Raw SQL: {sql}")
        process_time = time.time() - start_time
        span.record_exception(safety_error)
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="The AI generated a potentially unsafe SQL query.",
            headers={"X-Response-Time": f"{process_time:.6f} seconds"},
        )

    rows = await execute_ai_generated_sql(sql, client_dbconnection_pool)

    return SqlAgentResult(sql_template=sql_template, executed_sql=sql, rows=rows)
